import { Component, OnInit } from '@angular/core';
import { BannerImage, FaqSectionInfo } from '../../core/models';

@Component({
  selector: 'eyi-faq',
  templateUrl: './faq.component.html',
  styleUrls: ['./faq.component.scss']
})
export class FaqComponent implements OnInit {
  faqBanner: BannerImage = {
    image: './assets/images/Carousel_2.JPG',
    title: 'FAQ',
    description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.'
  };
  faqSectionInfo: FaqSectionInfo = {
    title: 'Frequently Asked Questions',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.',
    faqs: [
      {title: 'I have only practiced yoga rarely. Am I capable for a teacher training course?', description: 'Everest welcomes students of all age groups and experience levels. Yoga creates physical and mental balance, and we intend that everyone shares the experience and joy of yoga with our experienced teachers and most importantly from each other. However, to join our Teacher Training Courses, the minimum age requirement is twelve years.'},
      {title: 'Why should I choose a yoga teacher training program at your center only?', description: '<div>Although there are many Yoga Teacher Training programs located all over the world, there is something very special about participating at “Everest Yoga Institute” in India. We provide:</div><ul class="pt-4 eyi-style-type-none"><li>#Trial Classes</li><li>#Online & Offline Availability</li><li>#Yoga for Starters, Movers, Flyers</li><li>#Internationally Certified & Experienced Facilitators</li><li>#Study Material</li><li>#Focus on Traditional & Modern Yoga</li><li>#Multistyle Yoga</li><li>#Correct Techniques & Alignment</li><li>#Variations in Asanas</li><li>#Theme based Lesson Plans</li><li>#Internship Program</li><li>#Interdisciplinary Approach</li><li>#Life Time Registration</li></ul>'},
      {title: 'Are your online programs as effective as onsite programs?', description: 'We have designed our online courses in an effective manner, such that the student gets the schedule of the classes, links, study material and all-important information in a streamlined way. The students get the contact information of the coordinators, in case they need any support.'},
      {title: 'Can I extend my stay or program?', description: '<p>Programme extensions are possible by mutual agreement and depend on room and course availability. If you feel like staying longer and practicing with us, you are more than welcome!!</p><p>Please bear in mind that this is not included in the initial course fee.</p>'},
      {title: 'How do I sign up if I want to join?', description: '<p>If you wish to join our institute and you think it is the right fit for you,</p><p>call or whatsapp us at +919501934391/92</p><p>Or</p><p>email at <strong>yogainstituteeverest@gmail.com</strong>.</p><p>We will send you a personalized follow up email within 1-2 days.</p>'},
      {title: 'How would I come to know which program would be best for me? What do you suggest?', description: 'We recommend you to read the various program details and get a sense for what attracts you most. Feel free to contact us any time. Our 200hr Yoga Teacher Training is a perfect fit for starters as well as intermediate levels of practitioners. For more advanced training & deeper learning, you should first practice, experience and learn the basics.'},
      {title: 'Can I take the teacher training course if I am pregnant?', description: 'As Ashtanga Yoga & Everest Multistyle Yoga are a rigorous practice and our training courses are very intense, we strongly recommend that pregnant women consider taking our courses at a different time instead. If you come and find you’re pregnant, that’s fine too, we will do our best to accommodate your course post-delivery.'},
      {title: 'When should I arrive?', description: 'You can arrive near the days of your course date. We have a welcome ceremony and orientation meeting to ensure students know the schedule of classes, to familiarize with the facilities, and to allow students to meet each other and their teachers. Student attendance at the orientation day is compulsory.'},
      {title: 'Is it safe for a woman to travel alone in INDIA?', description: 'As India is surprisingly a safe country for women travelers. We have welcomed women of all ages to our courses who have traveled alone. There are certain codes of conduct that should be put in place to remain safe. We would say – keep emergency contact numbers handy on your phone, have confidence, be strong and carry yourself with a sense of dignity and self-respect, and be respectful of the culture in your dress and speech during your journey.'},
      {title: 'Do I need any vaccinations?', description: 'COVID 19 vaccinations are required to enter into India. You can check the status of vaccination requirements on an authorized online portal of Govt. Of India. We advise you to check with a travel doctor to see which vaccinations they recommend.'},
      {title: 'What type of clothing should I bring?', description: 'Starting from December and throughout the February, it can be very chilly before sunrise and after sunset. March weather is absolutely lovely during the day and a bit cold at night and in the early mornings. By April it starts getting hot. So it is best to pack thin, loose fitting cotton clothing. We advise you to pack in layers. As a mark of respect to Indian culture, women can make sure that their attire should cover their shoulders and knees, to avoid unnecessary intrusive intention when they go in the town. But you are permitted to wear “western style” fitted spandex yoga clothing and/or tank tops or camisoles while you are at the yoga center.'},
      {title: 'How to handle money in INDIA', description: '<p>In India, the currency is rupees (INR). Always travel with some USD in cases of emergency, NOT TRAVELERS CHEQUE. You may exchange money or use an ATM at airport in Delhi. ATM fees are almost always cheaper than doing Foreign Currency Exchange at a counter at the airport. There are also ATMs in Ludhiana. The 500 note and 2000 note are the largest notes in India, so it is difficult to break these notes, especially the 2000 note outside the small restaurants, markets and hotels. Try to carry the smaller change so that it is easier to negotiate when you are shopping or travelling on rikshaws or buses. Google Pay, Paytm, PayPal are very safe and easy choices for payment.</p><p>Be sure to inform your banks and credit card companies that you will be traveling to India before you leave, to avoid fraud protection freezes.</p>'},
      {title: 'Do I need a visa for coming to India?', description: 'All U.S citizens need a valid passport and Indian visa to enter and exit India for any purpose. Contact your nearest India Embassy in your home country to inquire visa processing.'},
      {title: 'How do I reach Ludhiana?', description: '<p>The distance between Delhi and Ludhiana is about 315kms and there are three means of traveling from Delhi to Ludhiana.</p><ol><li><strong>BY BUS: </strong>The travel time from Delhi to Ludhiana is about 5 hours. You can directly catch the bus from Delhi and reach down to Ludhiana.</li><li><strong>BY TRAIN: </strong>The travel time from Delhi to Ludhiana is about 4 hours and 35 minutes. Take the train from the Delhi railway station and it will drop you at Ludhiana railway station.</li><li><strong>BY FLIGHT: </strong>For traveling to Ludhiana from Delhi, you need to board a flight from Delhi which will land in Chandigarh airport. From Chandigarh, you can take a bus or a cab to reach Ludhiana.</li></ol><p>From Delhi to Chandigarh, approximate flight duration is 50 minutes. Further, from Chandigarh to Ludhiana, it takes 1 hour 45 minutes by bus or taxi.</p>'},
      {title: 'What should I need to pack for India?', description: '<p>Pack lightly because you will find plenty of shops to buy inexpensive clothing and toiletries. Women have to be more mindful about clothing suggestions than men, to respect the local culture. Try to keep your shoulders & knees covered & wear loose clothing and not small skirts.</p><ul class="pt-4"><li>Pants (for yoga, town, travel, hiking)</li><li>Tops (for yoga, short or long sleeved, shirts for other activities)</li><li>Scarf (you may wish to wait to purchase in India), for warmth and covering up (inside temples, etc)</li><li>Outer layer (sweatshirt or light jacket/fleece)</li><li>Thick Jacket (for very cold winters)</li><li>Sleepwear</li><li>Hat, Sunglasses (the sun can be intense)</li><li>Under Garments</li><li>Thermic Underwear (to survive the winter in Ludhiana)</li><li>Winter caps</li><li>Large shawl (perfect to meditate in winter times)</li><li>Sleeping Bag</li><li>Sweaters</li><li>Pair of Socks</li><li>Tennis Shoes (something to hike and walk in)</li><li>Sandals (mostly prefer flip-flops for the accommodations and in town)</li><li>Swimwear (Modest for everyone. Most will swim in their yoga clothes, but if you prefer a bathing suit, board shorts for men and one-piece with a cover-up for women)</li></ul>'},
      {title: 'Notes about clothing', description: '<ul><li>Tight yoga pants and leggings are okay in the yoga hall.</li><li>Very affordable laundry service is available (women should be prepared to wash intimate apparel in their room).</li></ul>'},
      {title: 'Toiletry Suggestions', description: '<ul><li>Anti-bacterial wipes</li><li>Several packages of travel-sized tissue</li><li>Mosquito Repellent</li><li>Tampons (they may not be available here)</li><li>Nail clippers, tweezers, razor</li><li>Hand sanitizer</li><li>Sunscreen</li><li>Laundry soaps for hands, washing clothes (You can also buy here)</li><li>Travel packs of facial/body wipes</li></ul>'},
      {title: 'A note about toiletries', description: '<ul><li>Leave your hair dryers, curling and flat irons, etc at home. Even with adapters, they will overheat and create shocks/melting. A wide range of products are available in India, including local brands you may wish to try.</li><li>Medical Supplies- Please consult your medical provider for suggestions on what medicine you need to carry.</li><li>Broad spectrum antibiotic and antibiotic ointment.</li><li>Small travel-sized first-aid kit that includes band-aids and alcohol/antibacterial wipes.</li></ul>'},
      {title: 'A few notes about medical supplies', description: '<ul><li>Consider providing us with a list of any allergies, special medical conditions, prescription medicines, blood type, and insurance card and number.</li></ul><p class="pt-4">As it is a big commitment of time and money, we are here to provide you with the answers to any questions you may have about the course or travel to India.</p><p>Please do not hesitate to contact us if we have not answered your questions here!!!!!</p>'}
    ]
  };

  constructor() { }

  ngOnInit(): void {
  }

}
